# Generated by Django 4.2.7 on 2024-01-06 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import momos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='momomessage',
            fields=[
                ('reference_id', models.CharField(default=momos.models.generate_uuid, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('Updated_at', models.DateField(null=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('select', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('countrycode', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=10)),
                ('msg', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'momomessage',
            },
        ),
    ]
